@hostname = http://server.tomsdata.no:3001/api/v1/comments
@contentType = application/json

GET {{hostname}}
###
# @name getCommentByID
GET {{hostname}}/{{commentID}}

###
# @name newComment
POST {{hostname}}
Content-Type: {{contentType}}

{"comment":"hello dr ømma", "additional":"really real doctor"}
###
@commentID = {{newComment.response.body.$._id}}
PUT {{hostname}}/{{commentID}}
Content-Type: application/json

{"comment":"new commmment"}
###
DELETE {{hostname}}/{{commentID}}
